const l = require('./common/command')
const arraydata = require('./common/arraydata')
const sorting = require('./algorithm/sorting')

let testdata = arraydata.randomArrayUnique(5)
l.title('sorting.bubbleSort')
l.input('I: ' + testdata)
l.output('O: ' + sorting.bubbleSort(testdata))
l.emptyline('')

testdata = arraydata.randomArrayUnique(10)
l.title('sorting.bubbleSort2')
l.input('I: ' + testdata)
l.output('O: ' + sorting.bubbleSort2(testdata))
l.emptyline('')

testdata = arraydata.randomArrayUnique(15)
l.title('sorting.bubbleSort3')
l.input('I: ' + testdata)
l.output('O: ' + sorting.bubbleSort3(testdata))
l.emptyline('')

testdata = arraydata.randomArrayUnique(20)
l.title('sorting.bubbleSort3')
l.input('I: ' + testdata)
l.output('O: ' + sorting.bubbleSort3(testdata))
l.emptyline('')

testdata = arraydata.randomArrayUnique(10)
l.title('sorting.selectionSort')
l.input('I: ' + testdata)
l.output('O: ' + sorting.selectionSort(testdata))
l.emptyline('')
