const l = require('./common/command')
const arraydata = require('./common/arraydata')
const sorting = require('./algorithm/sorting')

let testdata = arraydata.randomArrayLengthUnique(10)
l.title('sorting.bubbleSort')
l.input('I: ' + testdata)
l.output('O: ' + sorting.bubbleSort(testdata))
l.emptyline('')

let testdata2 = arraydata.randomArrayLengthUnique(10)
l.title('sorting.bubbleSort2')
l.input('I: ' + testdata2)
l.output('O: ' + sorting.bubbleSort2(testdata2))
l.emptyline('')

let testdata3 = arraydata.randomArrayLengthUnique(10)
l.title('sorting.bubbleSort3')
l.input('I: ' + testdata3)
l.output('O: ' + sorting.bubbleSort3(testdata3))
l.emptyline('')
